<?php

add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_6766289632abd',
        'title' => 'Founder',
        'fields' => array(
            array(
                'key' => 'field_6766331026c94',
                'label' => 'Last Name',
                'name' => 'last_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67662896e358f',
                'label' => 'Intro',
                'name' => 'intro',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_676628c21d787',
                'label' => 'Bio',
                'name' => 'bio',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_67662b6e96620',
                'label' => 'Image',
                'name' => 'image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'medium',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'founder',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});

add_action('init', function () {
    register_post_type('founder', array(
        'labels' => array(
            'name' => 'Founders',
            'singular_name' => 'Founder',
            'menu_name' => 'Founders',
            'all_items' => 'All Founders',
            'edit_item' => 'Edit Founder',
            'view_item' => 'View Founder',
            'view_items' => 'View Founders',
            'add_new_item' => 'Add New Founder',
            'add_new' => 'Add New Founder',
            'new_item' => 'New Founder',
            'parent_item_colon' => 'Parent Founder:',
            'search_items' => 'Search Founders',
            'not_found' => 'No founders found',
            'not_found_in_trash' => 'No founders found in Trash',
            'archives' => 'Founder Archives',
            'attributes' => 'Founder Attributes',
            'insert_into_item' => 'Insert into founder',
            'uploaded_to_this_item' => 'Uploaded to this founder',
            'filter_items_list' => 'Filter founders list',
            'filter_by_date' => 'Filter founders by date',
            'items_list_navigation' => 'Founders list navigation',
            'items_list' => 'Founders list',
            'item_published' => 'Founder published.',
            'item_published_privately' => 'Founder published privately.',
            'item_reverted_to_draft' => 'Founder reverted to draft.',
            'item_scheduled' => 'Founder scheduled.',
            'item_updated' => 'Founder updated.',
            'item_link' => 'Founder Link',
            'item_link_description' => 'A link to a founder.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-businessperson',
        'supports' => array(
            0 => 'title',
            1 => 'custom-fields',
        ),
        'delete_with_user' => false,
    ));
});
